# Generated by Django 2.0.6 on 2019-04-08 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('email', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('user_mobile', models.CharField(default='', max_length=255)),
                ('user_dob', models.CharField(default='', max_length=255)),
                ('user_gender', models.CharField(default='', max_length=10)),
                ('user_email', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='', max_length=300)),
                ('conf_password', models.CharField(default='', max_length=300)),
                ('login_time', models.CharField(default='', max_length=255)),
                ('login_date', models.CharField(default='', max_length=255)),
                ('logout_time', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_register',
            name='user_role_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User_app.User_Role'),
        ),
        migrations.AddField(
            model_name='user_login',
            name='user_role_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User_app.User_Role'),
        ),
    ]
