# Generated by Django 2.0.6 on 2019-04-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='email',
        ),
        migrations.AddField(
            model_name='user_login',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='User_app.User_Register'),
        ),
    ]
